server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Using a relative path that works whether run from root or from within the module
          search-locations: file:./../config-repo,file:./backend/config-repo,file:../config-repo
